import type { Formula } from "@/lib/types";

export const FORMULAS: Formula[] = [
  {
    id: "unit-conversion",
    topicId: "quantities-units",
    name: "Unit Conversion (km/h to m/s)",
    expression: "speed(m/s) = speed(km/h) ÷ 3.6",
    variables: [
      { symbol: "speed(km/h)", meaning: "speed measured in kilometres per hour", unit: "km/h" },
      { symbol: "speed(m/s)", meaning: "speed measured in metres per second", unit: "m/s" },
    ],
    conditions: ["Use whenever converting between km/h and m/s."],
    rearrangements: ["speed(km/h) = speed(m/s) × 3.6"],
    example: "72 km/h ÷ 3.6 = 20 m/s",
    commonMistake: "Multiplying by 3.6 instead of dividing when converting km/h → m/s.",
    whenToUse: "Whenever a question mixes km/h with SI (m, s) quantities.",
    whenNotToUse: "Not needed if all quantities are already in consistent SI units.",
  },
  {
    id: "dimension-check",
    topicId: "quantities-units",
    name: "Dimensional Homogeneity",
    expression: "[LHS] = [RHS]",
    variables: [{ symbol: "[X]", meaning: "the dimension of quantity X (in terms of M, L, T)", unit: "—" }],
    conditions: ["Applies to check whether an equation could be physically valid."],
    rearrangements: [],
    example: "s = ut + ½at²: [L] = [L/T·T] + [L/T²·T²] = [L] + [L] ✓ consistent",
    commonMistake: "Assuming dimensional consistency proves an equation is fully correct (it only rules out obviously wrong ones; constants like ½ can't be checked this way).",
    whenToUse: "To check plausibility of an unfamiliar formula.",
    whenNotToUse: "Cannot be used to find numerical constants (e.g. ½, 2π).",
  },
  {
    id: "vector-resultant",
    topicId: "vectors",
    name: "Resultant of Two Perpendicular Vectors",
    expression: "R = √(A² + B²), θ = tan⁻¹(B/A)",
    variables: [
      { symbol: "R", meaning: "magnitude of the resultant vector", unit: "same as A, B" },
      { symbol: "A, B", meaning: "magnitudes of the two perpendicular component vectors", unit: "e.g. N, m/s" },
      { symbol: "θ", meaning: "angle of resultant from vector A", unit: "degrees or radians" },
    ],
    conditions: ["A and B must be perpendicular to each other."],
    rearrangements: ["A = R cosθ", "B = R sinθ"],
    example: "A = 3 N, B = 4 N → R = √(9+16) = 5 N",
    commonMistake: "Using this formula for non-perpendicular vectors (use the cosine rule instead).",
    whenToUse: "When combining two perpendicular components into a single resultant.",
    whenNotToUse: "When the two vectors are not at 90° to each other.",
  },
  {
    id: "vector-components",
    topicId: "vectors",
    name: "Resolving a Vector into Components",
    expression: "Vx = V cosθ, Vy = V sinθ",
    variables: [
      { symbol: "V", meaning: "magnitude of the vector", unit: "e.g. N, m/s" },
      { symbol: "θ", meaning: "angle measured from the horizontal (x) axis", unit: "degrees" },
      { symbol: "Vx, Vy", meaning: "horizontal and vertical components of V", unit: "same as V" },
    ],
    conditions: ["θ must be measured consistently from a defined reference axis."],
    rearrangements: ["V = √(Vx²+Vy²)", "θ = tan⁻¹(Vy/Vx)"],
    example: "V=10 N at 37°: Vx=10cos37°=8 N, Vy=10sin37°=6 N",
    commonMistake: "Swapping sine and cosine — check which component is adjacent vs opposite to θ.",
    whenToUse: "Whenever a force/velocity acts at an angle and horizontal/vertical effects are needed separately.",
    whenNotToUse: "Not needed if the vector already acts purely horizontally or vertically.",
  },
  {
    id: "avg-speed",
    topicId: "kinematics-basics",
    name: "Average Speed",
    expression: "average speed = total distance ÷ total time",
    variables: [
      { symbol: "distance", meaning: "total path length travelled", unit: "m" },
      { symbol: "time", meaning: "total time taken", unit: "s" },
    ],
    conditions: ["Always uses TOTAL distance, not displacement."],
    rearrangements: ["distance = speed × time", "time = distance ÷ speed"],
    example: "600 m in 120 s → average speed = 5 m/s",
    commonMistake: "Averaging two speeds directly when times (or distances) for each leg are unequal — must use total distance/total time.",
    whenToUse: "For total journeys covering a path, especially with direction changes.",
    whenNotToUse: "Not appropriate when direction of motion matters (use velocity).",
  },
  {
    id: "avg-velocity",
    topicId: "kinematics-basics",
    name: "Average Velocity",
    expression: "average velocity = displacement ÷ time",
    variables: [
      { symbol: "displacement", meaning: "straight-line change in position, with direction", unit: "m" },
      { symbol: "time", meaning: "time taken", unit: "s" },
    ],
    conditions: ["Displacement must be measured from start point to end point directly."],
    rearrangements: ["displacement = velocity × time"],
    example: "Displacement of 30 m East in 10 s → velocity = 3 m/s East",
    commonMistake: "Using distance travelled instead of net displacement.",
    whenToUse: "When direction and net change in position matter.",
    whenNotToUse: "Not for describing total ground covered (use speed).",
  },
  {
    id: "suvat-v-u-at",
    topicId: "suvat",
    name: "SUVAT: v = u + at",
    expression: "v = u + at",
    variables: [
      { symbol: "v", meaning: "final velocity", unit: "m/s" },
      { symbol: "u", meaning: "initial velocity", unit: "m/s" },
      { symbol: "a", meaning: "constant acceleration", unit: "m/s²" },
      { symbol: "t", meaning: "time taken", unit: "s" },
    ],
    conditions: ["Acceleration must be constant."],
    rearrangements: ["u = v − at", "a = (v−u)/t", "t = (v−u)/a"],
    example: "u=5, a=2, t=4 → v = 5+2(4)=13 m/s",
    commonMistake: "Applying this when acceleration changes over time.",
    whenToUse: "When u, a, t are known (or 3 of the 4 variables) and no displacement s is involved.",
    whenNotToUse: "When acceleration is not constant, or when s is the only other known/unknown (use a different SUVAT equation).",
  },
  {
    id: "suvat-s-ut-half-at2",
    topicId: "suvat",
    name: "SUVAT: s = ut + ½at²",
    expression: "s = ut + ½at²",
    variables: [
      { symbol: "s", meaning: "displacement", unit: "m" },
      { symbol: "u", meaning: "initial velocity", unit: "m/s" },
      { symbol: "a", meaning: "constant acceleration", unit: "m/s²" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
    conditions: ["Acceleration must be constant."],
    rearrangements: ["No simple direct rearrangement for t (quadratic in t); solve using the quadratic formula if needed."],
    example: "u=0, a=4, t=3 → s = 0+0.5(4)(9)=18 m",
    commonMistake: "Forgetting to square t, or forgetting the ½.",
    whenToUse: "When u, a, t are known and s is required (or vice-versa, needing the quadratic formula).",
    whenNotToUse: "When v (final velocity) is known/needed instead of t.",
  },
  {
    id: "suvat-v2-u2-2as",
    topicId: "suvat",
    name: "SUVAT: v² = u² + 2as",
    expression: "v² = u² + 2as",
    variables: [
      { symbol: "v", meaning: "final velocity", unit: "m/s" },
      { symbol: "u", meaning: "initial velocity", unit: "m/s" },
      { symbol: "a", meaning: "constant acceleration", unit: "m/s²" },
      { symbol: "s", meaning: "displacement", unit: "m" },
    ],
    conditions: ["Acceleration must be constant.", "Useful when time is unknown/not needed."],
    rearrangements: ["u = √(v²−2as)", "a = (v²−u²)/(2s)", "s = (v²−u²)/(2a)"],
    example: "u=0, a=10, s=5 → v²=0+2(10)(5)=100, v=10 m/s",
    commonMistake: "Forgetting to take the square root at the end, or forgetting v² means v-squared, not 2v.",
    whenToUse: "When time t is not given and not required.",
    whenNotToUse: "When time is the requested unknown.",
  },
  {
    id: "suvat-s-avg",
    topicId: "suvat",
    name: "SUVAT: s = ((u+v)/2)t",
    expression: "s = ((u + v)/2) × t",
    variables: [
      { symbol: "s", meaning: "displacement", unit: "m" },
      { symbol: "u, v", meaning: "initial and final velocity", unit: "m/s" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
    conditions: ["Acceleration must be constant (so that average velocity = (u+v)/2)."],
    rearrangements: ["t = 2s/(u+v)"],
    example: "u=2, v=8, t=3 → s = (2+8)/2 × 3 = 15 m",
    commonMistake: "Using this when acceleration is not uniform (average velocity formula would be invalid).",
    whenToUse: "When u, v, and t are known, and acceleration a is not needed.",
    whenNotToUse: "When acceleration is required as part of the answer (use another SUVAT equation).",
  },
  {
    id: "gradient-graph",
    topicId: "motion-graphs",
    name: "Gradient of a Motion Graph",
    expression: "gradient = Δy/Δx",
    variables: [
      { symbol: "Δy", meaning: "change in the vertical axis quantity", unit: "depends on graph" },
      { symbol: "Δx", meaning: "change in the horizontal axis (usually time)", unit: "s" },
    ],
    conditions: ["Line must be straight for a single gradient value; use a tangent for curves."],
    rearrangements: [],
    example: "On a v-t graph, rising from 0 to 20 m/s in 5 s: gradient = 20/5 = 4 m/s² (acceleration)",
    commonMistake: "Using two points on a curved graph as if the line were straight between them.",
    whenToUse: "To find velocity (from s-t graph) or acceleration (from v-t graph).",
    whenNotToUse: "Cannot give displacement directly from a v-t graph (use area instead).",
  },
  {
    id: "area-under-graph",
    topicId: "motion-graphs",
    name: "Area Under a Motion Graph",
    expression: "Area = ∫ y dx (or geometric shape area for straight lines)",
    variables: [
      { symbol: "y", meaning: "vertical axis quantity (e.g. velocity)", unit: "depends on graph" },
      { symbol: "x", meaning: "horizontal axis quantity (usually time)", unit: "s" },
    ],
    conditions: ["Works for straight or curved sections; split into simple shapes (triangles, rectangles, trapezia) when straight."],
    rearrangements: [],
    example: "Constant velocity 10 m/s for 6 s → area = 10×6 = 60 m (displacement)",
    commonMistake: "Applying 'area' to a displacement-time graph, which has no standard physical meaning.",
    whenToUse: "To find displacement from a v-t graph, or change in velocity from an a-t graph.",
    whenNotToUse: "Not meaningful on a displacement-time graph.",
  },
  {
    id: "projectile-time-of-flight",
    topicId: "projectiles",
    name: "Time of Flight",
    expression: "T = 2u sinθ / g",
    variables: [
      { symbol: "T", meaning: "total time in the air (returning to launch height)", unit: "s" },
      { symbol: "u", meaning: "initial speed of projection", unit: "m/s" },
      { symbol: "θ", meaning: "angle of projection above horizontal", unit: "degrees" },
      { symbol: "g", meaning: "acceleration due to gravity", unit: "m/s²" },
    ],
    conditions: ["Launch height = landing height.", "Air resistance neglected."],
    rearrangements: ["u = Tg/(2sinθ)"],
    example: "u=30, θ=40°, g=10 → T = 2(30)sin40°/10 ≈ 3.86 s",
    commonMistake: "Using the full speed u instead of its vertical component u sinθ.",
    whenToUse: "When launch and landing heights are equal.",
    whenNotToUse: "When launched from a height and landing at a different (usually lower) level — must use full SUVAT vertically instead.",
  },
  {
    id: "projectile-range",
    topicId: "projectiles",
    name: "Range of a Projectile",
    expression: "R = u²sin2θ / g",
    variables: [
      { symbol: "R", meaning: "horizontal distance travelled", unit: "m" },
      { symbol: "u", meaning: "initial speed", unit: "m/s" },
      { symbol: "θ", meaning: "angle of projection", unit: "degrees" },
      { symbol: "g", meaning: "gravitational acceleration", unit: "m/s²" },
    ],
    conditions: ["Launch and landing at the same height; no air resistance."],
    rearrangements: [],
    example: "u=20, θ=45°, g=10 → R = 400×sin90°/10 = 40 m (maximum range at 45°)",
    commonMistake: "Applying when launch/landing heights differ.",
    whenToUse: "Quick calculation of horizontal range for equal launch/landing height.",
    whenNotToUse: "When heights differ — resolve into components and use SUVAT instead.",
  },
  {
    id: "projectile-max-height",
    topicId: "projectiles",
    name: "Maximum Height",
    expression: "H = (u sinθ)² / (2g)",
    variables: [
      { symbol: "H", meaning: "maximum height above launch point", unit: "m" },
      { symbol: "u", meaning: "initial speed", unit: "m/s" },
      { symbol: "θ", meaning: "angle of projection", unit: "degrees" },
      { symbol: "g", meaning: "gravitational acceleration", unit: "m/s²" },
    ],
    conditions: ["Applies at the point where vertical velocity = 0."],
    rearrangements: [],
    example: "u=20, θ=30°, g=10 → H = (10)²/20 = 5 m",
    commonMistake: "Forgetting to use only the vertical component (u sinθ), not full u.",
    whenToUse: "To find the peak height of any projectile's path.",
    whenNotToUse: "N/A — always valid for the vertical component of projectile motion.",
  },
  {
    id: "newtons-second-law",
    topicId: "newton-laws",
    name: "Newton's Second Law",
    expression: "F = ma",
    variables: [
      { symbol: "F", meaning: "resultant (net) force acting on the object", unit: "N" },
      { symbol: "m", meaning: "mass of the object", unit: "kg" },
      { symbol: "a", meaning: "resulting acceleration", unit: "m/s²" },
    ],
    conditions: ["F must be the RESULTANT of all forces.", "Mass must be constant (otherwise use F=Δp/Δt)."],
    rearrangements: ["a = F/m", "m = F/a"],
    example: "F=20 N, m=4 kg → a = 5 m/s²",
    commonMistake: "Using a single applied force instead of the resultant of ALL forces (including friction, gravity, etc).",
    whenToUse: "Whenever resultant force, mass or acceleration is required and mass is constant.",
    whenNotToUse: "When mass is changing (e.g. rocket burning fuel) — use F = Δp/Δt instead.",
  },
  {
    id: "weight-formula",
    topicId: "newton-laws",
    name: "Weight",
    expression: "W = mg",
    variables: [
      { symbol: "W", meaning: "weight (gravitational force on the object)", unit: "N" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "g", meaning: "gravitational field strength / acceleration due to gravity", unit: "N/kg or m/s²" },
    ],
    conditions: ["g varies with location (≈9.81 N/kg on Earth's surface, less on the Moon, in orbit, etc.)"],
    rearrangements: ["m = W/g"],
    example: "m=5 kg, g=10 → W = 50 N",
    commonMistake: "Treating mass and weight as the same physical quantity (mass is constant everywhere; weight changes with g).",
    whenToUse: "To convert between mass and weight at a known location.",
    whenNotToUse: "N/A within a single gravitational field, but g must be updated for different locations (Moon, orbit, etc).",
  },
  {
    id: "friction-force",
    topicId: "friction",
    name: "Friction Force",
    expression: "F(friction) ≤ μN (F = μN at the limiting/kinetic case)",
    variables: [
      { symbol: "F(friction)", meaning: "frictional force", unit: "N" },
      { symbol: "μ", meaning: "coefficient of friction (static or kinetic)", unit: "no units" },
      { symbol: "N", meaning: "normal reaction force between the surfaces", unit: "N" },
    ],
    conditions: ["μ depends on the pair of surfaces in contact.", "Use N (actual normal reaction), not weight, unless they are equal."],
    rearrangements: ["μ = F/N", "N = F/μ"],
    example: "μ=0.4, N=50 N → maximum friction = 20 N",
    commonMistake: "Assuming friction always equals μN, even when the object is in equilibrium below the limiting case.",
    whenToUse: "To find the maximum available friction, or friction during actual sliding (kinetic).",
    whenNotToUse: "To find friction on a stationary object NOT on the point of sliding (there, friction = whatever balances other forces, up to μN).",
  },
  {
    id: "incline-forces",
    topicId: "friction",
    name: "Forces on an Inclined Plane",
    expression: "Along slope: mg sinθ; Perpendicular: N = mg cosθ",
    variables: [
      { symbol: "m", meaning: "mass of object", unit: "kg" },
      { symbol: "g", meaning: "gravitational acceleration", unit: "m/s²" },
      { symbol: "θ", meaning: "angle of incline from horizontal", unit: "degrees" },
      { symbol: "N", meaning: "normal reaction, perpendicular to slope", unit: "N" },
    ],
    conditions: ["θ measured from the horizontal ground to the slope surface."],
    rearrangements: ["θ = tan⁻¹(F(along)/N)"],
    example: "m=10kg, θ=30°: along-slope = 10×10×sin30°=50N; N=10×10×cos30°=86.6N",
    commonMistake: "Using sinθ and cosθ swapped for the along-slope and perpendicular components.",
    whenToUse: "For any object on a slope (ramp, hill, inclined plane problems).",
    whenNotToUse: "N/A for horizontal or vertical surfaces (use those simpler cases directly).",
  },
  {
    id: "momentum-def",
    topicId: "momentum-impulse",
    name: "Momentum",
    expression: "p = mv",
    variables: [
      { symbol: "p", meaning: "momentum", unit: "kg m/s" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "v", meaning: "velocity", unit: "m/s" },
    ],
    conditions: ["Momentum is a vector — direction matters."],
    rearrangements: ["m = p/v", "v = p/m"],
    example: "m=1000kg, v=15m/s → p=15000 kg m/s",
    commonMistake: "Treating momentum as a scalar and ignoring direction in multi-object problems.",
    whenToUse: "Whenever motion quantity/impact is being analysed, especially collisions.",
    whenNotToUse: "N/A — always valid, but must track direction/sign carefully.",
  },
  {
    id: "impulse-def",
    topicId: "momentum-impulse",
    name: "Impulse",
    expression: "J = FΔt = Δp",
    variables: [
      { symbol: "J", meaning: "impulse", unit: "N s (equivalent to kg m/s)" },
      { symbol: "F", meaning: "force applied", unit: "N" },
      { symbol: "Δt", meaning: "time for which the force acts", unit: "s" },
      { symbol: "Δp", meaning: "change in momentum produced", unit: "kg m/s" },
    ],
    conditions: ["F is assumed constant, or an average force over Δt."],
    rearrangements: ["F = Δp/Δt", "Δt = Δp/F"],
    example: "Δp=50 kg m/s over Δt=0.2s → average F = 250 N",
    commonMistake: "Forgetting impulse equals CHANGE in momentum, not momentum itself.",
    whenToUse: "For impact/collision problems, especially involving force-time graphs or safety analysis.",
    whenNotToUse: "N/A, but check whether F is constant or you need an average value.",
  },
  {
    id: "conservation-momentum",
    topicId: "momentum-impulse",
    name: "Conservation of Momentum",
    expression: "m1u1 + m2u2 = m1v1 + m2v2",
    variables: [
      { symbol: "m1, m2", meaning: "masses of the two bodies", unit: "kg" },
      { symbol: "u1, u2", meaning: "initial velocities before interaction", unit: "m/s" },
      { symbol: "v1, v2", meaning: "final velocities after interaction", unit: "m/s" },
    ],
    conditions: ["No external resultant force during the interaction (collision/explosion)."],
    rearrangements: ["Solve for any single unknown velocity or mass algebraically."],
    example: "m1=2kg u1=3m/s, m2=2kg u2=0 (perfectly inelastic): v = (2×3)/(4)=1.5 m/s",
    commonMistake: "Not assigning correct positive/negative signs for opposite directions.",
    whenToUse: "Collisions, explosions, recoil problems.",
    whenNotToUse: "When a significant external force (e.g. sustained friction over a long time) acts during the process.",
  },
  {
    id: "work-done",
    topicId: "work-energy-power",
    name: "Work Done",
    expression: "W = Fs cosθ",
    variables: [
      { symbol: "W", meaning: "work done", unit: "J" },
      { symbol: "F", meaning: "applied force", unit: "N" },
      { symbol: "s", meaning: "displacement of the object", unit: "m" },
      { symbol: "θ", meaning: "angle between force and displacement directions", unit: "degrees" },
    ],
    conditions: ["θ = 0° gives W = Fs (force along displacement)."],
    rearrangements: ["F = W/(s cosθ)", "s = W/(F cosθ)"],
    example: "F=50N, s=10m, θ=0° → W=500 J",
    commonMistake: "Forgetting cosθ when force and displacement are not parallel; using W=Fs blindly.",
    whenToUse: "Whenever a force causes (or resists) displacement.",
    whenNotToUse: "When force is perpendicular to displacement (θ=90°), work done = 0.",
  },
  {
    id: "kinetic-energy",
    topicId: "work-energy-power",
    name: "Kinetic Energy",
    expression: "KE = ½mv²",
    variables: [
      { symbol: "KE", meaning: "kinetic energy", unit: "J" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "v", meaning: "speed", unit: "m/s" },
    ],
    conditions: ["Valid at non-relativistic speeds (all Senior 6 mechanics contexts)."],
    rearrangements: ["v = √(2KE/m)", "m = 2KE/v²"],
    example: "m=2kg, v=5m/s → KE=½×2×25=25 J",
    commonMistake: "Forgetting to square the velocity, or forgetting the ½.",
    whenToUse: "For the energy any moving object possesses due to its motion.",
    whenNotToUse: "N/A; always valid for translational kinetic energy at these speeds.",
  },
  {
    id: "gpe",
    topicId: "work-energy-power",
    name: "Gravitational Potential Energy",
    expression: "GPE = mgh",
    variables: [
      { symbol: "GPE", meaning: "gravitational potential energy relative to a reference level", unit: "J" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "g", meaning: "gravitational acceleration", unit: "m/s²" },
      { symbol: "h", meaning: "height above the chosen reference level", unit: "m" },
    ],
    conditions: ["Valid near Earth's surface where g is approximately constant."],
    rearrangements: ["h = GPE/(mg)", "m = GPE/(gh)"],
    example: "m=10kg, h=3m, g=10 → GPE=300 J",
    commonMistake: "Forgetting GPE is relative — always state/assume a reference height.",
    whenToUse: "For height-based energy storage near Earth's surface.",
    whenNotToUse: "For large height changes (comparable to Earth's radius) — use GPE = −GMm/r instead.",
  },
  {
    id: "power-def",
    topicId: "work-energy-power",
    name: "Power",
    expression: "P = W/t = Fv",
    variables: [
      { symbol: "P", meaning: "power", unit: "W" },
      { symbol: "W", meaning: "work done (or energy transferred)", unit: "J" },
      { symbol: "t", meaning: "time taken", unit: "s" },
      { symbol: "F", meaning: "driving force", unit: "N" },
      { symbol: "v", meaning: "velocity (constant speed case)", unit: "m/s" },
    ],
    conditions: ["P = Fv applies for instantaneous or constant-velocity motion."],
    rearrangements: ["W = Pt", "F = P/v"],
    example: "W=3000J, t=5s → P=600W",
    commonMistake: "Confusing power (rate) with energy/work (total amount).",
    whenToUse: "To find rate of energy transfer, e.g. engines, motors, lifting.",
    whenNotToUse: "N/A, but ensure consistent time units (convert minutes/hours to seconds).",
  },
  {
    id: "efficiency",
    topicId: "work-energy-power",
    name: "Efficiency",
    expression: "efficiency = (useful energy output / total energy input) × 100%",
    variables: [
      { symbol: "useful output", meaning: "energy converted to the intended useful form", unit: "J or W" },
      { symbol: "total input", meaning: "total energy supplied to the system", unit: "J or W" },
    ],
    conditions: ["Always ≤ 100% (energy is never created)."],
    rearrangements: ["useful output = efficiency × total input"],
    example: "Input=1000J, useful output=750J → efficiency=75%",
    commonMistake: "Getting an efficiency above 100%, indicating an arithmetic or conceptual error.",
    whenToUse: "To assess how much of the supplied energy becomes useful work in a machine/process.",
    whenNotToUse: "N/A.",
  },
  {
    id: "angular-velocity",
    topicId: "circular-motion",
    name: "Angular Velocity",
    expression: "ω = θ/t = 2π/T = 2πf; v = rω",
    variables: [
      { symbol: "ω", meaning: "angular velocity", unit: "rad/s" },
      { symbol: "θ", meaning: "angle swept", unit: "rad" },
      { symbol: "T", meaning: "period (time for one revolution)", unit: "s" },
      { symbol: "f", meaning: "frequency of revolution", unit: "Hz" },
      { symbol: "v", meaning: "linear (tangential) speed", unit: "m/s" },
      { symbol: "r", meaning: "radius of the circular path", unit: "m" },
    ],
    conditions: ["Angle must be measured in radians for these direct relations."],
    rearrangements: ["T = 2π/ω", "r = v/ω"],
    example: "T=4s → ω=2π/4=1.57 rad/s",
    commonMistake: "Using degrees instead of radians.",
    whenToUse: "Relating rotational rate to linear speed around a circle.",
    whenNotToUse: "N/A, just track units carefully.",
  },
  {
    id: "centripetal-acceleration",
    topicId: "circular-motion",
    name: "Centripetal Acceleration",
    expression: "a = v²/r = ω²r",
    variables: [
      { symbol: "a", meaning: "centripetal (radial) acceleration, directed toward the centre", unit: "m/s²" },
      { symbol: "v", meaning: "linear speed", unit: "m/s" },
      { symbol: "r", meaning: "radius", unit: "m" },
      { symbol: "ω", meaning: "angular velocity", unit: "rad/s" },
    ],
    conditions: ["Speed must be constant (uniform circular motion) for this simple form."],
    rearrangements: ["v = √(ar)", "r = v²/a"],
    example: "v=6m/s, r=3m → a=36/3=12 m/s²",
    commonMistake: "Using diameter instead of radius.",
    whenToUse: "Whenever an object moves in a circular path at constant speed.",
    whenNotToUse: "If speed is changing, there's also a tangential acceleration component (beyond this simple formula).",
  },
  {
    id: "centripetal-force",
    topicId: "circular-motion",
    name: "Centripetal Force",
    expression: "F = mv²/r = mω²r",
    variables: [
      { symbol: "F", meaning: "resultant force directed toward the centre, causing circular motion", unit: "N" },
      { symbol: "m", meaning: "mass of the object", unit: "kg" },
      { symbol: "v", meaning: "linear speed", unit: "m/s" },
      { symbol: "r", meaning: "radius of the circular path", unit: "m" },
    ],
    conditions: ["This F is the RESULTANT of real forces (tension, friction, gravity, normal reaction, etc), not an extra applied force."],
    rearrangements: ["v = √(Fr/m)", "r = mv²/F"],
    example: "m=2kg, v=4m/s, r=2m → F=2×16/2=16 N",
    commonMistake: "Adding centripetal force as an extra force in a free body diagram.",
    whenToUse: "Whenever finding the net inward force required to maintain circular motion.",
    whenNotToUse: "Never treat as an independent applied force to be drawn on a diagram.",
  },
  {
    id: "newton-gravitation",
    topicId: "gravitation-fields",
    name: "Newton's Law of Universal Gravitation",
    expression: "F = Gm1m2/r²",
    variables: [
      { symbol: "F", meaning: "gravitational force of attraction between two masses", unit: "N" },
      { symbol: "G", meaning: "universal gravitational constant", unit: "6.67×10⁻¹¹ N m²/kg²" },
      { symbol: "m1, m2", meaning: "the two masses", unit: "kg" },
      { symbol: "r", meaning: "distance between the centres of the two masses", unit: "m" },
    ],
    conditions: ["Applies exactly to point masses, and to uniform spheres measuring r from their centres."],
    rearrangements: ["r = √(Gm1m2/F)"],
    example: "m1=6×10²⁴kg, m2=70kg, r=6.4×10⁶m → F≈686N",
    commonMistake: "Using diameter or surface distance instead of centre-to-centre distance r.",
    whenToUse: "Any two-mass gravitational attraction problem, including planetary and satellite contexts.",
    whenNotToUse: "N/A at Senior 6 level (relativistic corrections not required).",
  },
  {
    id: "field-strength",
    topicId: "gravitation-fields",
    name: "Gravitational Field Strength",
    expression: "g = F/m = GM/r²",
    variables: [
      { symbol: "g", meaning: "gravitational field strength at a point", unit: "N/kg (equivalent to m/s²)" },
      { symbol: "F", meaning: "gravitational force on a small test mass", unit: "N" },
      { symbol: "m", meaning: "the small test mass", unit: "kg" },
      { symbol: "M", meaning: "mass of the body creating the field (e.g. planet)", unit: "kg" },
      { symbol: "r", meaning: "distance from the centre of M", unit: "m" },
    ],
    conditions: ["r must be measured from the centre of the mass creating the field."],
    rearrangements: ["M = gr²/G"],
    example: "M=6×10²⁴kg, r=6.4×10⁶m → g≈9.77 N/kg",
    commonMistake: "Using Earth's surface value g=9.8 for orbital altitudes far above the surface.",
    whenToUse: "To find the strength of gravity at any distance from a mass.",
    whenNotToUse: "N/A, just recompute r for each new location.",
  },
  {
    id: "orbital-velocity",
    topicId: "gravitation-fields",
    name: "Orbital Velocity",
    expression: "v = √(GM/r)",
    variables: [
      { symbol: "v", meaning: "orbital (tangential) speed for a stable circular orbit", unit: "m/s" },
      { symbol: "G", meaning: "gravitational constant", unit: "N m²/kg²" },
      { symbol: "M", meaning: "mass of the central body", unit: "kg" },
      { symbol: "r", meaning: "orbital radius (from centre of M)", unit: "m" },
    ],
    conditions: ["Assumes a stable circular orbit where gravity supplies exactly the centripetal force."],
    rearrangements: ["M = v²r/G", "r = GM/v²"],
    example: "M=6×10²⁴kg, r=6.8×10⁶m → v≈7.67 km/s",
    commonMistake: "Forgetting to take the square root, or using diameter instead of radius.",
    whenToUse: "For circular orbit speed calculations (satellites, planets, moons).",
    whenNotToUse: "For elliptical orbits (requires more advanced treatment, beyond this level).",
  },
  {
    id: "geostationary",
    topicId: "gravitation-fields",
    name: "Kepler's Third Law (Orbital Period)",
    expression: "T² = 4π²r³ / (GM)",
    variables: [
      { symbol: "T", meaning: "orbital period", unit: "s" },
      { symbol: "r", meaning: "orbital radius", unit: "m" },
      { symbol: "G", meaning: "gravitational constant", unit: "N m²/kg²" },
      { symbol: "M", meaning: "mass of the central body", unit: "kg" },
    ],
    conditions: ["Circular orbit assumption."],
    rearrangements: ["r = (GMT²/4π²)^(1/3)"],
    example: "For geostationary orbit, T=24h=86400s gives r≈4.22×10⁷ m",
    commonMistake: "Forgetting to convert period to seconds before substituting.",
    whenToUse: "Relating orbital period to orbital radius for any satellite.",
    whenNotToUse: "N/A for circular orbits at this level.",
  },
  {
    id: "moment-def",
    topicId: "moments-equilibrium",
    name: "Moment of a Force",
    expression: "Moment = F × d",
    variables: [
      { symbol: "Moment", meaning: "turning effect of the force about a pivot", unit: "N m" },
      { symbol: "F", meaning: "applied force", unit: "N" },
      { symbol: "d", meaning: "perpendicular distance from the pivot to the line of action of F", unit: "m" },
    ],
    conditions: ["d must be the PERPENDICULAR distance, not just any distance."],
    rearrangements: ["F = Moment/d", "d = Moment/F"],
    example: "F=20N, d=0.5m → Moment=10 N m",
    commonMistake: "Using the distance along the object rather than the perpendicular distance to the force's line of action.",
    whenToUse: "To quantify any turning/rotational effect of a force.",
    whenNotToUse: "N/A, always applicable to any pivoted system.",
  },
  {
    id: "principle-of-moments",
    topicId: "moments-equilibrium",
    name: "Principle of Moments",
    expression: "ΣClockwise moments = ΣAnticlockwise moments",
    variables: [
      { symbol: "Clockwise/Anticlockwise moments", meaning: "sum of (F×d) for forces turning each way about the chosen pivot", unit: "N m" },
    ],
    conditions: ["Body must be in rotational equilibrium (not angularly accelerating)."],
    rearrangements: ["Solve for any single unknown force or distance algebraically."],
    example: "30N×1.5m = W×2m → W=22.5N",
    commonMistake: "Forgetting the weight of a non-uniform or off-centre-pivoted beam also creates a moment.",
    whenToUse: "Beam, see-saw, ladder and lever balance problems.",
    whenNotToUse: "N/A, but always also check force equilibrium separately.",
  },
  {
    id: "shm-acceleration",
    topicId: "shm-oscillations",
    name: "SHM Acceleration",
    expression: "a = −ω²x",
    variables: [
      { symbol: "a", meaning: "acceleration, directed toward equilibrium", unit: "m/s²" },
      { symbol: "ω", meaning: "angular frequency", unit: "rad/s" },
      { symbol: "x", meaning: "displacement from equilibrium position", unit: "m" },
    ],
    conditions: ["Defines SHM: acceleration must be proportional to displacement and oppositely directed."],
    rearrangements: ["ω = √(−a/x)", "x = −a/ω²"],
    example: "ω=2rad/s, x=0.1m → a=−0.4 m/s² (directed back to centre)",
    commonMistake: "Dropping the negative sign, losing the 'restoring' nature of the acceleration.",
    whenToUse: "To find instantaneous acceleration at a known displacement in SHM.",
    whenNotToUse: "N/A for true SHM systems (springs, pendulums at small angle).",
  },
  {
    id: "shm-period-spring",
    topicId: "shm-oscillations",
    name: "Period of a Mass-Spring System",
    expression: "T = 2π√(m/k)",
    variables: [
      { symbol: "T", meaning: "period of oscillation", unit: "s" },
      { symbol: "m", meaning: "oscillating mass", unit: "kg" },
      { symbol: "k", meaning: "spring constant", unit: "N/m" },
    ],
    conditions: ["Spring obeys Hooke's law; mass of spring itself is negligible."],
    rearrangements: ["k = 4π²m/T²", "m = kT²/4π²"],
    example: "m=0.2kg, k=8N/m → T=2π√(0.025)≈0.99s",
    commonMistake: "Forgetting to square root the mass/k ratio.",
    whenToUse: "For any ideal mass-spring oscillator.",
    whenNotToUse: "If the spring's own mass is significant, or amplitude is so large Hooke's law fails.",
  },
  {
    id: "shm-period-pendulum",
    topicId: "shm-oscillations",
    name: "Period of a Simple Pendulum",
    expression: "T = 2π√(l/g)",
    variables: [
      { symbol: "T", meaning: "period of oscillation", unit: "s" },
      { symbol: "l", meaning: "length of the pendulum", unit: "m" },
      { symbol: "g", meaning: "gravitational acceleration", unit: "m/s²" },
    ],
    conditions: ["Valid for small angle oscillations (typically < 10°); string is light and inextensible; bob treated as a point mass."],
    rearrangements: ["g = 4π²l/T²", "l = gT²/4π²"],
    example: "l=1m, g=10 → T=2π√0.1≈1.99s",
    commonMistake: "Using this formula for large-amplitude swings, where it becomes inaccurate.",
    whenToUse: "Small-angle simple pendulum problems.",
    whenNotToUse: "Large amplitude swings, or pendulums with significant bob size/string mass.",
  },
  {
    id: "hookes-law",
    topicId: "elasticity-hooke",
    name: "Hooke's Law",
    expression: "F = kx",
    variables: [
      { symbol: "F", meaning: "applied (stretching/compressing) force", unit: "N" },
      { symbol: "k", meaning: "spring constant (stiffness)", unit: "N/m" },
      { symbol: "x", meaning: "extension (or compression) from natural length", unit: "m" },
    ],
    conditions: ["Only valid up to the elastic limit of the material."],
    rearrangements: ["k = F/x", "x = F/k"],
    example: "k=100N/m, x=0.05m → F=5N",
    commonMistake: "Applying F=kx beyond the elastic limit where the relationship is no longer linear.",
    whenToUse: "Any spring/elastic material within its elastic region.",
    whenNotToUse: "Beyond the elastic limit (plastic deformation region).",
  },
  {
    id: "youngs-modulus",
    topicId: "elasticity-hooke",
    name: "Young's Modulus",
    expression: "E = stress/strain = (F/A)/(x/L)",
    variables: [
      { symbol: "E", meaning: "Young's Modulus (measure of stiffness of the material)", unit: "Pa (N/m²)" },
      { symbol: "F", meaning: "applied force", unit: "N" },
      { symbol: "A", meaning: "cross-sectional area", unit: "m²" },
      { symbol: "x", meaning: "extension", unit: "m" },
      { symbol: "L", meaning: "original length", unit: "m" },
    ],
    conditions: ["Only valid within the elastic (Hookean) region of the material."],
    rearrangements: ["x = FL/(AE)", "F = EAx/L"],
    example: "F=200N, A=2×10⁻⁶m², x=0.001m, L=2m → E=2×10¹¹ Pa",
    commonMistake: "Using diameter instead of cross-sectional area (A = πr² for a wire).",
    whenToUse: "To compare stiffness of different materials, or find extension of a loaded wire.",
    whenNotToUse: "Beyond the elastic limit of the material.",
  },
  {
    id: "elastic-energy",
    topicId: "elasticity-hooke",
    name: "Elastic Potential Energy",
    expression: "E = ½kx² = ½Fx",
    variables: [
      { symbol: "E", meaning: "elastic potential energy stored", unit: "J" },
      { symbol: "k", meaning: "spring constant", unit: "N/m" },
      { symbol: "x", meaning: "extension", unit: "m" },
      { symbol: "F", meaning: "force at that extension (=kx)", unit: "N" },
    ],
    conditions: ["Valid while the material obeys Hooke's Law (straight-line force-extension graph)."],
    rearrangements: ["x = √(2E/k)", "k = 2E/x²"],
    example: "k=200N/m, x=0.1m → E=0.5×200×0.01=1J",
    commonMistake: "Using E=Fx (forgetting the ½, which accounts for the force increasing linearly from zero).",
    whenToUse: "To find energy stored in / released by a stretched or compressed elastic object.",
    whenNotToUse: "Beyond the elastic limit, where the graph is no longer a straight line (energy = actual area under the curve instead).",
  },
];

export function searchFormulas(query: string): Formula[] {
  const q = query.trim().toLowerCase();
  if (!q) return FORMULAS;
  return FORMULAS.filter(
    (f) =>
      f.name.toLowerCase().includes(q) ||
      f.expression.toLowerCase().includes(q) ||
      f.variables.some((v) => v.symbol.toLowerCase().includes(q) || v.meaning.toLowerCase().includes(q)) ||
      (f.tags ?? []).some((t) => t.toLowerCase().includes(q))
  );
}

export function getFormulasByTopic(topicId: string): Formula[] {
  return FORMULAS.filter((f) => f.topicId === topicId);
}
