import type { GlossaryTerm } from "@/lib/types";

export const GLOSSARY: GlossaryTerm[] = [
  { id: "distance", term: "Distance", simple: "How far you actually walked or travelled, ignoring direction.", formal: "Total length of the path travelled by a body.", unit: "m", example: "Walking around a 400m track once = 400 m distance." },
  { id: "displacement", term: "Displacement", simple: "How far you ended up from where you started, in a straight line.", formal: "The change in position of a body in a specified direction; the shortest straight line from start to end point.", formula: "Δs = s_final − s_initial", unit: "m", example: "Walking around a 400m track once ends with 0 m displacement." },
  { id: "speed", term: "Speed", simple: "How fast you cover ground.", formal: "The rate of change of distance with time (scalar).", formula: "speed = distance/time", unit: "m/s", example: "A car covering 100 m in 5 s has a speed of 20 m/s." },
  { id: "velocity", term: "Velocity", simple: "How fast you move in a certain direction.", formal: "The rate of change of displacement with time (vector).", formula: "velocity = displacement/time", unit: "m/s", example: "20 m/s due East." },
  { id: "acceleration", term: "Acceleration", simple: "How quickly your velocity is changing.", formal: "The rate of change of velocity with time (vector).", formula: "a = (v − u)/t", unit: "m/s²", example: "A car speeding up from 0 to 20 m/s in 4 s has a = 5 m/s²." },
  { id: "mass", term: "Mass", simple: "The amount of matter (stuff) in an object; how hard it is to speed up or slow down.", formal: "A scalar measure of a body's inertia — its resistance to changes in motion.", unit: "kg", example: "A bag of cement has a mass of 50 kg, everywhere in the universe." },
  { id: "weight", term: "Weight", simple: "How hard gravity pulls you down; changes depending on where you are.", formal: "The gravitational force acting on a body's mass.", formula: "W = mg", unit: "N", example: "A 50 kg bag has weight 500 N on Earth, but only about 83 N on the Moon." },
  { id: "momentum", term: "Momentum", simple: "How hard it is to stop something that's moving — depends on both mass and speed.", formal: "The product of an object's mass and velocity; a vector quantity.", formula: "p = mv", unit: "kg m/s", example: "A truck moving slowly can have more momentum than a car moving fast." },
  { id: "impulse", term: "Impulse", simple: "A push (force) applied for some time, changing an object's momentum.", formal: "The product of force and the time for which it acts; equal to the change in momentum produced.", formula: "J = FΔt = Δp", unit: "N s", example: "A footballer's kick applies an impulse that changes the ball's momentum from zero to some large value." },
  { id: "inertia", term: "Inertia", simple: "An object's 'laziness' — its natural tendency to keep doing whatever it's already doing.", formal: "The property of matter that resists any change in its state of motion; proportional to mass.", unit: "—", example: "Passengers lurch forward when a bus suddenly stops, because their bodies resist the change in motion." },
  { id: "tension", term: "Tension", simple: "The pulling force transmitted through a string, rope, or cable.", formal: "The force exerted by a stretched string/rope/cable/spring, acting along its length, pulling inward on whatever it's attached to.", unit: "N", example: "The tension in a crane's cable supports the weight of a suspended load." },
  { id: "friction", term: "Friction", simple: "A force that resists sliding between two touching surfaces.", formal: "The force opposing relative motion (or the tendency of relative motion) between two surfaces in contact.", formula: "F ≤ μN", unit: "N", example: "Friction between shoes and the ground lets a sprinter push off and accelerate." },
  { id: "resultant", term: "Resultant Force", simple: "The single overall force left over after combining all forces acting on an object.", formal: "The vector sum of all forces acting on a body.", unit: "N", example: "If a 10 N push acts right and 4 N friction acts left, the resultant is 6 N to the right." },
  { id: "moment", term: "Moment", simple: "The 'turning power' of a force around a pivot.", formal: "The turning effect of a force, equal to force multiplied by the perpendicular distance from the pivot to the line of action of the force.", formula: "Moment = F × d", unit: "N m", example: "Pushing a door far from its hinges needs less force to open it than pushing near the hinges." },
  { id: "torque", term: "Torque", simple: "Another name for the turning effect of a force (often used for rotating machinery/couples).", formal: "The rotational equivalent of force; equal to a moment or the effect of a couple.", formula: "τ = F × d", unit: "N m", example: "A car engine's torque determines how strongly it can turn the wheels." },
  { id: "equilibrium", term: "Equilibrium", simple: "A balanced state — nothing is speeding up, slowing down, or starting to turn.", formal: "A state in which the resultant force AND resultant moment on a body are both zero.", unit: "—", example: "A parked car, or a book resting on a table, are both in equilibrium." },
  { id: "centripetal-force-term", term: "Centripetal Force", simple: "The inward force needed to keep something moving in a circle.", formal: "The resultant force directed toward the centre of a circular path, required to produce centripetal acceleration.", formula: "F = mv²/r", unit: "N", example: "Friction supplies the centripetal force for a car turning a corner." },
  { id: "gravitational-field", term: "Gravitational Field", simple: "The invisible region around any mass where it pulls other masses toward it.", formal: "A region of space in which a mass experiences a gravitational force.", formula: "g = F/m", unit: "N/kg", example: "Earth's gravitational field pulls a dropped stone downward." },
  { id: "potential", term: "Gravitational Potential", simple: "How much 'stored energy per kg' a location has due to gravity, compared to being infinitely far away.", formal: "The work done per unit mass to bring a small test mass from infinity to that point in a gravitational field.", formula: "V = −GM/r", unit: "J/kg", example: "Points closer to Earth have more negative (lower) gravitational potential." },
  { id: "work-term", term: "Work", simple: "Energy transferred when a force moves something.", formal: "The product of force and displacement in the direction of the force.", formula: "W = Fs cosθ", unit: "J", example: "Lifting a bag of maize up a flight of stairs does work against gravity." },
  { id: "energy-term", term: "Energy", simple: "The capacity to do work or cause change.", formal: "A scalar physical quantity representing the capacity of a system to do work; conserved in all interactions.", unit: "J", example: "Fuel stores chemical energy, converted to kinetic energy as a car speeds up." },
  { id: "power-term", term: "Power", simple: "How quickly work is done or energy is transferred.", formal: "The rate of doing work, or the rate of transfer of energy.", formula: "P = W/t", unit: "W", example: "A more powerful motor lifts the same load in less time." },
  { id: "stress-term", term: "Stress", simple: "How much 'squeeze' or 'pull' force is spread over a material's cross-section.", formal: "Force applied per unit cross-sectional area of a material.", formula: "stress = F/A", unit: "Pa", example: "A thin wire experiences higher stress than a thick one under the same load." },
  { id: "strain-term", term: "Strain", simple: "How much a material stretches, compared to its original length.", formal: "The ratio of extension to original length of a material.", formula: "strain = x/L", unit: "no units", example: "A wire stretching from 2.00 m to 2.02 m has a strain of 0.01." },
  { id: "elasticity-term", term: "Elasticity", simple: "The ability of a material to return to its original shape after a force is removed.", formal: "The property of a material that enables it to resist deformation and return to its original size and shape after the deforming force is removed.", unit: "—", example: "A rubber band is highly elastic; wet clay is not." },
  { id: "amplitude", term: "Amplitude", simple: "The maximum distance an oscillating object moves from its resting position.", formal: "The maximum displacement from the equilibrium position in an oscillation.", unit: "m", example: "A pendulum swinging 10 cm to each side has amplitude 10 cm." },
  { id: "period-term", term: "Period", simple: "The time taken for one complete back-and-forth oscillation.", formal: "The time taken to complete one full cycle of oscillation.", formula: "T = 1/f", unit: "s", example: "A pendulum's period is roughly 2 seconds if it is 1 metre long." },
  { id: "frequency-term", term: "Frequency", simple: "How many oscillations happen every second.", formal: "The number of complete oscillations per unit time.", formula: "f = 1/T", unit: "Hz", example: "A guitar string vibrating 440 times a second has frequency 440 Hz." },
];

export function searchGlossary(query: string): GlossaryTerm[] {
  const q = query.trim().toLowerCase();
  if (!q) return GLOSSARY;
  return GLOSSARY.filter(
    (g) => g.term.toLowerCase().includes(q) || g.simple.toLowerCase().includes(q) || g.formal.toLowerCase().includes(q)
  );
}
