import type { Question } from "@/lib/types";

// Curated, hand-verified questions covering every topic and a spread of
// difficulty/type. Combined at runtime with the procedural generators in
// generators.ts to give a very large effective question pool.
export const QUESTION_BANK: Question[] = [
  // ---------------- QUANTITIES & UNITS ----------------
  {
    id: "qu-1", topicId: "quantities-units", subtopic: "Unit conversion", difficulty: "easy", type: "calculation",
    prompt: "Convert 108 km/h to m/s.",
    correctAnswer: "30 m/s", tolerance: 0.5,
    hints: { hint1: "Think about how many metres are in a km, and seconds in an hour.", hint2: "Use the shortcut: divide km/h by 3.6.", hint3: "108 ÷ 3.6 = ?" },
    solution: {
      given: ["speed = 108 km/h"], find: "speed in m/s",
      principle: "1 km = 1000 m, 1 hour = 3600 s.",
      formula: "speed(m/s) = speed(km/h) / 3.6",
      whyFormula: "Dividing by 3.6 combines converting km→m (×1000) and h→s (÷3600) into one step.",
      substitution: "108 / 3.6", calculation: ["108 / 3.6 = 30"], units: "m/s",
      finalAnswer: "30 m/s", meaning: "This is a fairly fast highway speed — about 30 metres covered every second.",
    },
    commonMistakes: ["Multiplying by 3.6 instead of dividing."], tags: ["units"],
  },
  {
    id: "qu-2", topicId: "quantities-units", subtopic: "Dimensions", difficulty: "medium", type: "conceptual",
    prompt: "Which of the following is a derived quantity?",
    choices: ["Mass", "Time", "Force", "Length"], correctIndex: 2, correctAnswer: "Force",
    hints: { hint1: "Base quantities cannot be broken into simpler ones.", hint2: "Force = mass × acceleration.", hint3: "Acceleration itself combines length and time." },
    solution: {
      given: ["Options: Mass, Time, Force, Length"], find: "Which is a derived quantity",
      principle: "Base quantities (mass, length, time, etc.) are fundamental; derived quantities are combinations of base quantities.",
      formula: "Force = mass × acceleration = kg·m/s²",
      whyFormula: "Force's SI unit (kg m/s²) is clearly built from the base units of mass, length and time.",
      substitution: "N/A", calculation: ["Mass, time and length are base quantities.", "Force = mass × acceleration, so it's derived."],
      units: "N = kg m/s²", finalAnswer: "Force", meaning: "Force cannot be measured directly with a single fundamental standard; it's calculated from mass, length and time.",
    },
    commonMistakes: ["Confusing base and derived quantities."], tags: ["dimensions"],
  },

  // ---------------- VECTORS ----------------
  {
    id: "vec-1", topicId: "vectors", subtopic: "Resolution of vectors", difficulty: "easy", type: "calculation",
    prompt: "A force of 50 N acts at 60° above the horizontal. Find its horizontal component.",
    correctAnswer: "25 N", tolerance: 1,
    hints: { hint1: "The horizontal component is adjacent to the given angle.", hint2: "Use Fx = F cos θ.", hint3: "cos 60° = 0.5" },
    solution: {
      given: ["F = 50 N", "θ = 60° above horizontal"], find: "Horizontal component Fx",
      principle: "Resolving a vector along perpendicular axes using trigonometry.",
      formula: "Fx = F cos θ",
      whyFormula: "The horizontal component is the side of the force triangle adjacent to θ, given by cosine.",
      substitution: "Fx = 50 × cos 60°", calculation: ["cos60° = 0.5", "Fx = 50 × 0.5 = 25 N"],
      units: "N", finalAnswer: "25 N", meaning: "Only 25 N of the force actually acts horizontally; the rest acts vertically.",
    },
    commonMistakes: ["Using sine instead of cosine for the horizontal component."], tags: ["vectors"],
  },
  {
    id: "vec-2", topicId: "vectors", subtopic: "Vector addition", difficulty: "medium", type: "calculation",
    prompt: "Two forces, 30 N due East and 40 N due North, act on a point object. Find the magnitude of the resultant force.",
    correctAnswer: "50 N", tolerance: 1,
    hints: { hint1: "The two forces are perpendicular.", hint2: "Use Pythagoras' theorem.", hint3: "R² = 30² + 40²" },
    solution: {
      given: ["F1 = 30 N East", "F2 = 40 N North"], find: "Magnitude of resultant force",
      principle: "Perpendicular vectors combine using Pythagoras' theorem.",
      formula: "R = √(F1² + F2²)",
      whyFormula: "Since the two forces are at 90° to each other, they form the two legs of a right-angled triangle whose hypotenuse is the resultant.",
      substitution: "R = √(30² + 40²)", calculation: ["30² = 900, 40² = 1600", "900+1600 = 2500", "√2500 = 50"],
      units: "N", finalAnswer: "50 N", meaning: "The combined pulling effect of both forces is equivalent to a single 50 N force acting at some angle between East and North.",
    },
    commonMistakes: ["Simply adding 30+40=70 N, ignoring the perpendicular directions."], tags: ["vectors"],
  },
  {
    id: "vec-3", topicId: "vectors", subtopic: "Equilibrium of forces", difficulty: "hard", type: "scenario",
    scenario: "A shop sign of weight 80 N hangs from two ropes, each making 40° with the horizontal ceiling, attached at the same point on the sign.",
    prompt: "Find the tension in each rope, assuming the system is symmetric and in equilibrium.",
    correctAnswer: "62.2 N", tolerance: 2,
    hints: { hint1: "By symmetry, both ropes have equal tension.", hint2: "Resolve each tension into vertical components; they must together support the weight.", hint3: "2T sin40° = 80 N" },
    solution: {
      given: ["Weight W = 80 N", "Each rope at 40° to horizontal", "Symmetric system"], find: "Tension T in each rope",
      principle: "For equilibrium, the sum of vertical force components must equal the weight; horizontal components cancel by symmetry.",
      formula: "2T sinθ = W",
      whyFormula: "Each rope's vertical component is T sinθ; with two identical ropes sharing the load symmetrically, twice that must balance gravity.",
      substitution: "2T sin40° = 80", calculation: ["sin40° = 0.643", "2T(0.643) = 80", "T = 80/1.286 = 62.2 N"],
      units: "N", finalAnswer: "T ≈ 62.2 N", meaning: "Each rope must be strong enough to bear about 62.2 N — more than half the sign's weight, because the ropes are angled rather than vertical.",
    },
    commonMistakes: ["Assuming each rope simply carries half the weight (40 N) — this ignores the angle."], tags: ["vectors", "equilibrium"],
  },

  // ---------------- KINEMATICS BASICS ----------------
  {
    id: "kb-1", topicId: "kinematics-basics", subtopic: "Distance vs displacement", difficulty: "beginner", type: "conceptual",
    prompt: "A student walks 8 m East then 6 m West. What is the total distance travelled and the displacement?",
    correctAnswer: "Distance = 14 m; Displacement = 2 m East", tolerance: 0,
    hints: { hint1: "Distance adds up every metre walked, regardless of direction.", hint2: "Displacement only cares about start and end position.", hint3: "8 − 6 = 2" },
    solution: {
      given: ["8 m East then 6 m West"], find: "Distance and displacement",
      principle: "Distance sums path length; displacement is net change of position.",
      formula: "distance = sum of path lengths; displacement = final position − initial position",
      whyFormula: "These are the definitions of each quantity — distance ignores direction, displacement depends on it.",
      substitution: "distance = 8+6; displacement = 8 − 6 (East positive)",
      calculation: ["distance = 14 m", "displacement = 8 − 6 = 2 m East"],
      units: "m", finalAnswer: "Distance = 14 m, Displacement = 2 m East",
      meaning: "The student walked 14 m in total but ended up only 2 m from where they started.",
    },
    commonMistakes: ["Reporting displacement as 14 m (same as distance)."], tags: ["kinematics"],
  },
  {
    id: "kb-2", topicId: "kinematics-basics", subtopic: "Average speed", difficulty: "medium", type: "calculation",
    prompt: "A matatu travels 60 km in 1 hour, then 40 km in 30 minutes. Find its average speed for the whole journey in km/h.",
    correctAnswer: "66.7 km/h", tolerance: 1,
    hints: { hint1: "Average speed = total distance / total time.", hint2: "Convert 30 minutes to hours (0.5 h).", hint3: "Total distance = 100 km, total time = 1.5 h." },
    solution: {
      given: ["60 km in 1 h", "40 km in 0.5 h"], find: "Average speed for the whole journey",
      principle: "Average speed uses TOTAL distance divided by TOTAL time, not the average of the two individual speeds.",
      formula: "average speed = total distance / total time",
      whyFormula: "The two legs have different times, so simply averaging 60 km/h and 80 km/h would be incorrect.",
      substitution: "(60+40)/(1+0.5)", calculation: ["total distance = 100 km", "total time = 1.5 h", "100/1.5 = 66.7 km/h"],
      units: "km/h", finalAnswer: "66.7 km/h", meaning: "Even though the matatu was faster in the second leg, its overall average is pulled toward the longer first leg's speed.",
    },
    commonMistakes: ["Averaging 60 and 80 km/h directly to get 70 km/h."], tags: ["kinematics"],
  },

  // ---------------- SUVAT ----------------
  {
    id: "suv-1", topicId: "suvat", subtopic: "v = u + at", difficulty: "easy", type: "calculation",
    prompt: "A cyclist accelerates uniformly from 2 m/s to 10 m/s in 4 s. Find the acceleration.",
    correctAnswer: "2 m/s²", tolerance: 0.2,
    hints: { hint1: "You are given u, v, and t.", hint2: "Use a = (v − u)/t.", hint3: "(10 − 2)/4 = ?" },
    solution: {
      given: ["u = 2 m/s", "v = 10 m/s", "t = 4 s"], find: "acceleration a",
      principle: "Acceleration is the rate of change of velocity.",
      formula: "a = (v − u)/t",
      whyFormula: "We know u, v and t directly, and need a — this is the direct rearrangement of v = u + at.",
      substitution: "a = (10 − 2)/4", calculation: ["a = 8/4 = 2"],
      units: "m/s²", finalAnswer: "2 m/s²", meaning: "The cyclist's speed increases by 2 m/s every second.",
    },
    commonMistakes: ["Dividing by the wrong time value, or subtracting u and v the wrong way round."], tags: ["suvat"],
  },
  {
    id: "suv-2", topicId: "suvat", subtopic: "s = ut + ½at²", difficulty: "medium", type: "calculation",
    prompt: "A stone is dropped from rest and falls for 3 s. Taking g = 10 m/s², find the distance it falls.",
    correctAnswer: "45 m", tolerance: 1,
    hints: { hint1: "'Dropped from rest' means u = 0.", hint2: "Use s = ut + ½at² with a = g.", hint3: "s = 0 + 0.5 × 10 × 9" },
    solution: {
      given: ["u = 0 (dropped from rest)", "a = g = 10 m/s²", "t = 3 s"], find: "distance fallen s",
      principle: "Free fall is uniformly accelerated motion under gravity.",
      formula: "s = ut + ½at²",
      whyFormula: "We know u, a and t, and want s — this SUVAT equation links exactly those.",
      substitution: "s = 0(3) + 0.5(10)(3²)", calculation: ["3² = 9", "0.5 × 10 × 9 = 45"],
      units: "m", finalAnswer: "45 m", meaning: "The stone has fallen 45 m after 3 seconds — showing how quickly free-fall distance grows (proportional to t²).",
    },
    commonMistakes: ["Forgetting to square the time.", "Forgetting u=0 still needs to be included conceptually (though it contributes 0)."], tags: ["suvat", "free fall"],
  },
  {
    id: "suv-3", topicId: "suvat", subtopic: "v² = u² + 2as", difficulty: "hard", type: "scenario",
    scenario: "A car brakes from 25 m/s and comes to rest after skidding 50 m.",
    prompt: "Find the car's deceleration.",
    correctAnswer: "6.25 m/s²", tolerance: 0.3,
    hints: { hint1: "'Comes to rest' means final velocity v = 0.", hint2: "Time is not given or needed — use v² = u² + 2as.", hint3: "0 = 25² + 2a(50), solve for a." },
    solution: {
      given: ["u = 25 m/s", "v = 0 (comes to rest)", "s = 50 m"], find: "deceleration a",
      principle: "Time isn't given, so use the SUVAT equation that excludes time.",
      formula: "v² = u² + 2as",
      whyFormula: "We know u, v, and s but not t — this is the only SUVAT equation without t.",
      substitution: "0² = 25² + 2a(50)", calculation: ["0 = 625 + 100a", "a = −625/100 = −6.25"],
      units: "m/s²", finalAnswer: "6.25 m/s² (deceleration, i.e. negative acceleration)", meaning: "The car slows down at a rate of 6.25 m/s² every second until it stops — this magnitude helps assess whether the braking was safe.",
    },
    commonMistakes: ["Forgetting the negative sign showing this is a deceleration.", "Using s=ut+½at² unnecessarily when a simpler equation works directly."], tags: ["suvat", "braking"],
  },
  {
    id: "suv-4", topicId: "suvat", subtopic: "Exam-style multistep", difficulty: "exam", type: "multistep",
    scenario: "A train starts from rest at a station and accelerates uniformly at 0.5 m/s² for 20 s, then travels at constant speed for 60 s, then decelerates uniformly to rest in 10 s.",
    prompt: "Find the total distance travelled by the train.",
    correctAnswer: "800 m", tolerance: 10,
    hints: { hint1: "Split the journey into 3 separate stages.", hint2: "Find the speed reached at the end of stage 1 first.", hint3: "Use s=ut+½at² for stage 1, s=vt for stage 2, and s=((u+v)/2)t for stage 3." },
    solution: {
      given: ["Stage 1: u=0, a=0.5 m/s², t=20 s", "Stage 2: constant velocity, t=60 s", "Stage 3: decelerates to rest, t=10 s"],
      find: "Total distance travelled",
      principle: "Break multi-stage motion into separate uniform-acceleration phases and apply SUVAT to each.",
      formula: "Stage1: s=ut+½at²; Stage2: s=vt; Stage3: s=((u+v)/2)t",
      whyFormula: "Each phase has constant acceleration (0.5, 0, and some negative value), so SUVAT can be applied separately to each, then distances summed.",
      substitution: "v(after stage1) = 0+0.5(20) = 10 m/s",
      calculation: [
        "Stage 1: s1 = 0(20)+0.5(0.5)(20²) = 0.25×400 = 100 m",
        "Speed at end of stage 1 = u+at = 0+0.5×20 = 10 m/s",
        "Stage 2: s2 = 10 × 60 = 600 m",
        "Stage 3: s3 = ((10+0)/2) × 10 = 5×10 = 50 m",
        "Total = 100+600+50 = 750 m",
      ],
      units: "m", finalAnswer: "750 m",
      meaning: "Even though this looks complex, breaking the journey into three simple constant-acceleration stages makes it manageable — this is the standard exam technique for multi-stage motion.",
    },
    commonMistakes: ["Trying to apply one single SUVAT equation to the whole journey (invalid, since acceleration changes between stages).", "Forgetting to find the speed at the end of stage 1 before starting stage 2."],
    tags: ["suvat", "multistage"],
  },

  // ---------------- MOTION GRAPHS ----------------
  {
    id: "mg-1", topicId: "motion-graphs", subtopic: "Gradient", difficulty: "easy", type: "graph",
    prompt: "A displacement-time graph is a straight line rising from 0 m to 40 m over 8 s. What is the velocity?",
    correctAnswer: "5 m/s", tolerance: 0.2,
    hints: { hint1: "Gradient of a displacement-time graph = velocity.", hint2: "Gradient = rise/run.", hint3: "40/8 = ?" },
    solution: {
      given: ["s-t graph: straight line from (0,0) to (8,40)"], find: "velocity",
      principle: "Gradient of a displacement-time graph gives velocity.",
      formula: "velocity = Δs/Δt",
      whyFormula: "By definition, velocity is the rate of change of displacement, which is exactly the graph's gradient.",
      substitution: "(40-0)/(8-0)", calculation: ["40/8 = 5"], units: "m/s",
      finalAnswer: "5 m/s", meaning: "The object moves at a steady 5 m/s throughout, since the line is straight (constant gradient).",
    },
    commonMistakes: ["Calculating 'area' instead of gradient for a displacement-time graph."], tags: ["graphs"],
  },
  {
    id: "mg-2", topicId: "motion-graphs", subtopic: "Area under v-t graph", difficulty: "medium", type: "graph",
    prompt: "A velocity-time graph shows a constant velocity of 15 m/s for 10 s, followed by uniform deceleration to rest over the next 5 s. Find the total distance travelled.",
    correctAnswer: "187.5 m", tolerance: 3,
    hints: { hint1: "Split the graph into a rectangle and a triangle.", hint2: "Area of rectangle = 15×10.", hint3: "Area of triangle = ½×5×15." },
    solution: {
      given: ["Constant v=15 m/s for 10 s", "Then decelerates to 0 over 5 s"], find: "total distance (area under graph)",
      principle: "Area under a velocity-time graph equals distance travelled.",
      formula: "Total area = rectangle + triangle",
      whyFormula: "The area under each straight-line segment of a v-t graph corresponds exactly to the distance covered in that segment.",
      substitution: "Rectangle = 15×10; Triangle = ½×5×15",
      calculation: ["Rectangle = 150 m", "Triangle = 0.5×5×15 = 37.5 m", "Total = 150+37.5 = 187.5 m"],
      units: "m", finalAnswer: "187.5 m", meaning: "The object covers 150 m while cruising, then a further 37.5 m while braking to a stop.",
    },
    commonMistakes: ["Forgetting to include both the rectangle AND triangle sections."], tags: ["graphs"],
  },

  // ---------------- PROJECTILES ----------------
  {
    id: "proj-1", topicId: "projectiles", subtopic: "Horizontal projection", difficulty: "easy", type: "calculation",
    prompt: "A ball is thrown horizontally at 15 m/s from a cliff 20 m high. Taking g=10 m/s², find the time it takes to reach the ground.",
    correctAnswer: "2 s", tolerance: 0.1,
    hints: { hint1: "Horizontal speed doesn't affect the time of fall.", hint2: "Only the vertical motion determines when it lands.", hint3: "Use s=ut+½at² vertically, with u=0 vertically." },
    solution: {
      given: ["Horizontal speed = 15 m/s (irrelevant to time of fall)", "Height h=20 m", "g=10 m/s²", "Initial vertical velocity = 0"],
      find: "Time to reach the ground",
      principle: "Vertical and horizontal motions are independent; time of flight depends only on the vertical fall.",
      formula: "h = ½gt²",
      whyFormula: "Vertically, the ball starts with zero vertical velocity and accelerates downward at g, exactly like a dropped object.",
      substitution: "20 = 0.5(10)t²", calculation: ["20 = 5t²", "t² = 4", "t = 2"],
      units: "s", finalAnswer: "2 s", meaning: "Regardless of how fast it was thrown horizontally, the ball takes 2 seconds to fall 20 m, exactly as if it had simply been dropped.",
    },
    commonMistakes: ["Trying to use the horizontal speed (15 m/s) in the vertical time calculation."], tags: ["projectiles"],
  },
  {
    id: "proj-2", topicId: "projectiles", subtopic: "Angled projection", difficulty: "hard", type: "multistep",
    prompt: "A footballer kicks a ball at 18 m/s at 35° above the horizontal. Taking g=10 m/s², find (a) the maximum height reached and (b) the range.",
    correctAnswer: "H ≈ 5.34 m; R ≈ 30.5 m", tolerance: 1,
    hints: { hint1: "Resolve the initial velocity into horizontal and vertical components first.", hint2: "Use H=(u sinθ)²/2g and R=u²sin2θ/g.", hint3: "u sin35° ≈ 10.3 m/s" },
    solution: {
      given: ["u = 18 m/s", "θ = 35°", "g = 10 m/s²"], find: "Maximum height H and range R",
      principle: "Vertical component controls height and time of flight; both components together control range.",
      formula: "H = (u sinθ)²/(2g); R = u² sin2θ / g",
      whyFormula: "These are the standard projectile results derived from resolving u into components and applying SUVAT vertically, combined with constant horizontal velocity.",
      substitution: "u sin35° = 18×0.574 = 10.3; H=10.3²/20; R=18²×sin70°/10",
      calculation: [
        "H = 106.1/20 ≈ 5.3 m",
        "sin70° ≈ 0.940",
        "R = 324 × 0.940/10 ≈ 30.5 m",
      ],
      units: "H in m, R in m", finalAnswer: "H ≈ 5.3 m, R ≈ 30.5 m",
      meaning: "The ball rises just over 5 m into the air and lands about 30.5 m away — a realistic long football pass.",
    },
    commonMistakes: ["Using u instead of the vertical component u sinθ in the height formula.", "Using θ instead of 2θ in the range formula."], tags: ["projectiles"],
  },

  // ---------------- NEWTON'S LAWS ----------------
  {
    id: "nl-1", topicId: "newton-laws", subtopic: "F = ma", difficulty: "easy", type: "calculation",
    prompt: "A resultant force of 60 N acts on a 12 kg object. Find its acceleration.",
    correctAnswer: "5 m/s²", tolerance: 0.2,
    hints: { hint1: "Use Newton's Second Law.", hint2: "a = F/m", hint3: "60/12 = ?" },
    solution: {
      given: ["F = 60 N", "m = 12 kg"], find: "acceleration a",
      principle: "Newton's Second Law: resultant force produces a proportional acceleration.",
      formula: "a = F/m",
      whyFormula: "Direct rearrangement of F=ma for a, since F and m are known.",
      substitution: "a = 60/12", calculation: ["a = 5"], units: "m/s²",
      finalAnswer: "5 m/s²", meaning: "For every second, the object's velocity increases by 5 m/s in the direction of the resultant force.",
    },
    commonMistakes: ["Dividing mass by force instead of force by mass."], tags: ["newton"],
  },
  {
    id: "nl-2", topicId: "newton-laws", subtopic: "Newton's Third Law", difficulty: "medium", type: "conceptual",
    prompt: "A book of weight 20 N rests on a table. Which force forms the Newton's Third Law reaction pair to the book's weight?",
    choices: [
      "The Normal reaction of the table on the book (20 N upward)",
      "The gravitational pull of the book on the Earth (20 N upward, acting on Earth)",
      "Friction between the book and table",
      "There is no reaction pair for weight",
    ],
    correctIndex: 1, correctAnswer: "The gravitational pull of the book on the Earth (20 N upward, acting on Earth)",
    hints: { hint1: "Third law pairs act on DIFFERENT objects.", hint2: "Weight is the Earth pulling the book down — what does the book do to the Earth?", hint3: "The book must pull the Earth up, by Newton's Third Law." },
    solution: {
      given: ["Book weight = 20 N (Earth pulling book down)"], find: "The Newton's Third Law reaction pair to weight",
      principle: "Newton's Third Law pairs are equal, opposite, and act on DIFFERENT objects, and are of the SAME TYPE of force.",
      formula: "Action: Earth pulls book (gravity). Reaction: book pulls Earth (gravity).",
      whyFormula: "The Normal reaction is a contact force response to weight in equilibrium, but it is a DIFFERENT TYPE of force acting on the book, not the book's Third Law partner. The true partner must also be gravitational, and act on the Earth.",
      substitution: "N/A", calculation: ["Weight acts on the book (from Earth).", "Its Third Law pair is the book's gravitational pull on the Earth, equal in size (20N) but opposite in direction."],
      units: "N", finalAnswer: "The gravitational pull of the book on the Earth (20 N upward, acting on the Earth)",
      meaning: "The Normal reaction balances the book's weight for EQUILIBRIUM purposes, but it is not its Newton's Third Law partner — that must be the same TYPE of force (gravity) acting on the other object (Earth).",
    },
    commonMistakes: ["Confusing the Normal reaction (an equilibrium partner) with the true Newton's Third Law reaction pair (must be same force type, opposite object)."], tags: ["newton", "misconception"],
  },
  {
    id: "nl-3", topicId: "newton-laws", subtopic: "Connected particles", difficulty: "hard", type: "scenario",
    scenario: "Two blocks, A (5 kg) and B (3 kg), are connected by a light inextensible string over a frictionless pulley at the edge of a table. Block A is on the table (frictionless), Block B hangs freely.",
    prompt: "Find the acceleration of the system and the tension in the string. (g=10 m/s²)",
    correctAnswer: "a = 3.75 m/s², T = 18.75 N", tolerance: 0.3,
    hints: { hint1: "Only B's weight drives the system, but BOTH masses must be accelerated.", hint2: "Treat the system as one, or write two equations (one per mass) and combine.", hint3: "a = (m_B g)/(m_A+m_B)" },
    solution: {
      given: ["m_A = 5 kg (on frictionless table)", "m_B = 3 kg (hanging)", "g = 10 m/s²", "String inextensible, pulley frictionless"],
      find: "Acceleration a and tension T",
      principle: "Newton's Second Law applied to the whole connected system, and separately to isolate the tension.",
      formula: "a = m_B g / (m_A+m_B); T = m_A a",
      whyFormula: "Treating the system as a whole, only B's weight provides a net driving force (A has no friction/gravity component along the table), but the total mass being accelerated is (m_A+m_B). Then isolating A alone (frictionless, horizontal) shows the only horizontal force on A is the tension T, giving T=m_A a.",
      substitution: "a = (3×10)/(5+3); T = 5×a",
      calculation: ["a = 30/8 = 3.75 m/s²", "T = 5 × 3.75 = 18.75 N"],
      units: "a in m/s², T in N", finalAnswer: "a = 3.75 m/s², T = 18.75 N",
      meaning: "Both blocks accelerate together at 3.75 m/s² — slower than B would fall alone (which would be 10 m/s²) because it must also drag block A along the table via the string tension.",
    },
    commonMistakes: ["Using only m_B in F=ma instead of the total mass (m_A+m_B) for the system.", "Forgetting the tension is LESS than B's weight (since B is accelerating, not in equilibrium)."],
    tags: ["newton", "pulley", "connected particles"],
  },

  // ---------------- FRICTION ----------------
  {
    id: "fr-1", topicId: "friction", subtopic: "Coefficient of friction", difficulty: "easy", type: "calculation",
    prompt: "A 20 kg box is dragged along a horizontal floor at constant velocity by a horizontal force of 40 N. Find the coefficient of kinetic friction. (g=10 m/s²)",
    correctAnswer: "0.2", tolerance: 0.02,
    hints: { hint1: "Constant velocity means the resultant force is zero, so friction = applied force.", hint2: "Normal reaction N = weight = mg on a horizontal floor.", hint3: "μ = F/N" },
    solution: {
      given: ["m = 20 kg", "Applied force = 40 N", "constant velocity (equilibrium)", "g=10 m/s²"], find: "coefficient of kinetic friction μ",
      principle: "At constant velocity, friction exactly balances the applied force (Newton's First Law).",
      formula: "μ = F(friction)/N, where N = mg on a horizontal surface",
      whyFormula: "Equilibrium means friction = 40N; on a flat floor, Normal reaction simply balances weight.",
      substitution: "N = 20×10 = 200; μ = 40/200", calculation: ["μ = 0.2"],
      units: "no units", finalAnswer: "μ = 0.2", meaning: "This is a fairly low coefficient of friction, typical of a smooth floor.",
    },
    commonMistakes: ["Forgetting that constant velocity implies friction equals the applied force exactly."], tags: ["friction"],
  },
  {
    id: "fr-2", topicId: "friction", subtopic: "Inclined planes", difficulty: "hard", type: "scenario",
    scenario: "A 15 kg crate sits on a ramp inclined at 25° to the horizontal. The coefficient of static friction between crate and ramp is 0.5.",
    prompt: "Determine whether the crate will remain stationary or slide down the ramp.",
    correctAnswer: "It remains stationary (tan25° < μ)", tolerance: 0,
    hints: { hint1: "Compare tanθ with μ.", hint2: "If tanθ < μ, static friction can supply enough force to prevent sliding.", hint3: "tan25° ≈ 0.466" },
    solution: {
      given: ["θ = 25°", "μ (static) = 0.5", "m = 15 kg"], find: "Whether the crate slides",
      principle: "A body on a slope stays still if the maximum available static friction (μmg cosθ) is at least as large as the driving component of weight (mg sinθ), i.e. if tanθ ≤ μ.",
      formula: "Compare tanθ with μ",
      whyFormula: "Dividing mg sinθ ≤ μ mg cosθ by mg cosθ gives tanθ ≤ μ directly — this avoids even needing the mass or g explicitly.",
      substitution: "tan25° vs 0.5", calculation: ["tan25° ≈ 0.466", "0.466 < 0.5"],
      units: "no units (ratio)", finalAnswer: "The crate remains stationary, since tan25° (0.466) < μ (0.5)",
      meaning: "Static friction is just strong enough to hold the crate in place on this slope — but only just; a slightly steeper ramp would cause it to slide.",
    },
    commonMistakes: ["Assuming the crate always slides on any incline.", "Forgetting mass and g cancel out of the tanθ vs μ comparison."], tags: ["friction", "incline"],
  },

  // ---------------- FREE BODY DIAGRAMS ----------------
  {
    id: "fbd-1", topicId: "free-body-diagrams", subtopic: "Identifying forces", difficulty: "beginner", type: "conceptual",
    prompt: "A book rests on a rough horizontal table, with no other object touching it. How many distinct forces act on the book?",
    choices: ["1", "2", "3", "4"], correctIndex: 1, correctAnswer: "2",
    hints: { hint1: "Only forces acting ON the book count.", hint2: "There is no applied force or friction, since nothing is trying to slide it.", hint3: "Consider only weight and normal reaction." },
    solution: {
      given: ["Book at rest on a rough horizontal table, no other contact"], find: "Number of forces acting on the book",
      principle: "An FBD only includes forces acting on the chosen object; friction is only present if there's applied/tendency of sliding.",
      formula: "Forces = Weight + Normal reaction (no sliding tendency ⇒ no friction needed)",
      whyFormula: "With no horizontal applied force, there's no tendency to slide, so static friction is zero here — it is not 'always' present just because the surface is rough.",
      substitution: "N/A", calculation: ["Weight (down)", "Normal reaction (up)", "No friction acts since there's no sliding tendency"],
      units: "—", finalAnswer: "2 forces (weight and normal reaction)",
      meaning: "Even a rough table exerts zero friction on a book that isn't being pushed sideways — friction only appears to oppose an actual or tended sliding motion.",
    },
    commonMistakes: ["Assuming friction always acts on a 'rough' surface, even without an applied sideways force."], tags: ["fbd"],
  },

  // ---------------- MOMENTUM & IMPULSE ----------------
  {
    id: "mo-1", topicId: "momentum-impulse", subtopic: "Momentum", difficulty: "easy", type: "calculation",
    prompt: "Find the momentum of a 1200 kg car travelling at 20 m/s.",
    correctAnswer: "24000 kg m/s", tolerance: 200,
    hints: { hint1: "Use p = mv.", hint2: "Multiply mass by velocity directly.", hint3: "1200 × 20 = ?" },
    solution: {
      given: ["m = 1200 kg", "v = 20 m/s"], find: "momentum p",
      principle: "Momentum is the product of mass and velocity.",
      formula: "p = mv", whyFormula: "This is the direct definition of momentum.",
      substitution: "p = 1200 × 20", calculation: ["p = 24000"], units: "kg m/s",
      finalAnswer: "24000 kg m/s", meaning: "This large value shows why a moving car is so hard to stop suddenly — a large mass and speed combine into a large momentum.",
    },
    commonMistakes: ["Forgetting momentum's SI unit is kg m/s, not N or J."], tags: ["momentum"],
  },
  {
    id: "mo-2", topicId: "momentum-impulse", subtopic: "Conservation of momentum", difficulty: "medium", type: "calculation",
    prompt: "A 2 kg trolley moving at 3 m/s collides with a stationary 1 kg trolley. After collision they move apart, with the 1 kg trolley moving at 4 m/s in the original direction. Find the velocity of the 2 kg trolley after collision.",
    correctAnswer: "1 m/s", tolerance: 0.2,
    hints: { hint1: "Total momentum before = total momentum after.", hint2: "Momentum before: only the 2 kg trolley is moving.", hint3: "2(3)+1(0) = 2v + 1(4)" },
    solution: {
      given: ["m1=2kg, u1=3 m/s", "m2=1kg, u2=0", "v2 (after) = 4 m/s"], find: "v1 (velocity of 2kg trolley after collision)",
      principle: "Conservation of momentum applies since no external horizontal force acts during the brief collision.",
      formula: "m1u1 + m2u2 = m1v1 + m2v2",
      whyFormula: "This is the direct statement of momentum conservation for a two-body collision.",
      substitution: "2(3)+1(0) = 2v1 + 1(4)", calculation: ["6 = 2v1 + 4", "2v1 = 2", "v1 = 1"],
      units: "m/s", finalAnswer: "v1 = 1 m/s (same direction as before)",
      meaning: "The 2 kg trolley continues moving forward but much slower, having transferred a lot of its momentum to the lighter trolley.",
    },
    commonMistakes: ["Forgetting the stationary trolley's initial momentum is zero (still must be written in the equation for clarity).", "Sign errors if trolleys end up moving in opposite directions."], tags: ["momentum", "collisions"],
  },
  {
    id: "mo-3", topicId: "momentum-impulse", subtopic: "Impulse", difficulty: "hard", type: "scenario",
    scenario: "A 0.15 kg cricket ball travelling at 25 m/s is hit back in the opposite direction at 20 m/s by a bat. The contact time between bat and ball is 0.01 s.",
    prompt: "Find the average force exerted by the bat on the ball.",
    correctAnswer: "675 N", tolerance: 20,
    hints: { hint1: "Take one direction as positive; the ball reverses direction.", hint2: "Change in momentum = final momentum − initial momentum (careful with signs!).", hint3: "F = Δp/Δt" },
    solution: {
      given: ["m = 0.15 kg", "initial velocity = 25 m/s (say, positive)", "final velocity = −20 m/s (opposite direction)", "Δt = 0.01 s"],
      find: "Average force exerted by the bat",
      principle: "The bat's force produces an impulse equal to the ball's change in momentum.",
      formula: "F = Δp/Δt = m(v−u)/Δt",
      whyFormula: "Since the ball reverses direction, both the loss of forward momentum AND the gain of backward momentum must be accounted using signed velocities.",
      substitution: "F = 0.15×(−20−25)/0.01", calculation: ["−20−25 = −45", "0.15×(−45) = −6.75", "F = −6.75/0.01 = −675"],
      units: "N", finalAnswer: "675 N (directed back toward the bowler)",
      meaning: "The bat must exert a very large force (675 N) because it has to reverse the ball's momentum in a very short contact time (0.01 s) — this is why cricket bats and balls can produce painful impacts.",
    },
    commonMistakes: ["Forgetting the ball REVERSES direction, and using +20 instead of −20 for final velocity.", "Not dividing by the very small contact time correctly."], tags: ["momentum", "impulse"],
  },

  // ---------------- WORK, ENERGY, POWER ----------------
  {
    id: "we-1", topicId: "work-energy-power", subtopic: "Kinetic energy", difficulty: "easy", type: "calculation",
    prompt: "Find the kinetic energy of an 800 kg car moving at 20 m/s.",
    correctAnswer: "160000 J", tolerance: 2000,
    hints: { hint1: "Use KE = ½mv².", hint2: "Square the velocity first.", hint3: "0.5 × 800 × 400" },
    solution: {
      given: ["m = 800 kg", "v = 20 m/s"], find: "kinetic energy",
      principle: "Kinetic energy is the energy an object has due to its motion.",
      formula: "KE = ½mv²", whyFormula: "Direct application of the KE formula with known mass and velocity.",
      substitution: "KE = 0.5×800×20²", calculation: ["20² = 400", "0.5×800×400 = 160000"],
      units: "J", finalAnswer: "160,000 J (160 kJ)", meaning: "This is the amount of energy the car's brakes must dissipate as heat to bring it to a complete stop.",
    },
    commonMistakes: ["Forgetting to square the velocity (using v instead of v²)."], tags: ["energy"],
  },
  {
    id: "we-2", topicId: "work-energy-power", subtopic: "Conservation of energy", difficulty: "medium", type: "calculation",
    prompt: "A 2 kg ball is dropped from a height of 5 m. Ignoring air resistance, find its speed just before hitting the ground. (g=10 m/s²)",
    correctAnswer: "10 m/s", tolerance: 0.3,
    hints: { hint1: "GPE lost = KE gained (energy conservation).", hint2: "mgh = ½mv².", hint3: "Mass cancels out!" },
    solution: {
      given: ["m = 2 kg", "h = 5 m", "g = 10 m/s²", "no air resistance"], find: "speed just before impact",
      principle: "Conservation of mechanical energy: GPE lost equals KE gained when only gravity does work.",
      formula: "mgh = ½mv² ⟹ v = √(2gh)",
      whyFormula: "Since no energy is lost to air resistance, all lost potential energy converts directly into kinetic energy.",
      substitution: "v = √(2×10×5)", calculation: ["2×10×5 = 100", "√100 = 10"],
      units: "m/s", finalAnswer: "10 m/s", meaning: "Notice the mass cancelled out — all objects (ignoring air resistance) reach the same speed after falling the same height, regardless of mass.",
    },
    commonMistakes: ["Forgetting mass cancels, and unnecessarily trying to use the 2 kg value in the final answer.", "Confusing this with momentum conservation (different principle)."], tags: ["energy", "free fall"],
  },
  {
    id: "we-3", topicId: "work-energy-power", subtopic: "Power & efficiency", difficulty: "hard", type: "scenario",
    scenario: "A water pump lifts 300 kg of water to a tank 8 m high every minute. The pump's motor consumes electrical energy at a rate of 500 W.",
    prompt: "Find the efficiency of the pump. (g=10 m/s²)",
    correctAnswer: "80%", tolerance: 3,
    hints: { hint1: "First find the useful power output (rate of gaining GPE).", hint2: "Useful power = mgh/time.", hint3: "Efficiency = useful power / input power × 100%" },
    solution: {
      given: ["m = 300 kg per minute", "h = 8 m", "t = 60 s", "Input power = 500 W", "g=10 m/s²"],
      find: "Efficiency of the pump",
      principle: "Efficiency compares useful energy output rate to total energy input rate.",
      formula: "useful power = mgh/t; efficiency = (useful power/input power) × 100%",
      whyFormula: "The useful output of the pump is the gravitational PE given to the water each second; comparing this to the electrical power supplied gives efficiency.",
      substitution: "useful power = (300×10×8)/60; efficiency = (useful power/500)×100",
      calculation: ["300×10×8 = 24000 J", "24000/60 = 400 W (useful power)", "efficiency = (400/500)×100 = 80%"],
      units: "%", finalAnswer: "80%", meaning: "80% of the electrical energy supplied becomes useful gravitational PE in the lifted water; the remaining 20% is lost, mostly as heat in the motor and friction in moving parts.",
    },
    commonMistakes: ["Forgetting to convert 'per minute' into a per-second rate before comparing with the 500 W (which is already per second).", "Getting an efficiency above 100% (a sign of an arithmetic error)."], tags: ["energy", "power", "efficiency"],
  },

  // ---------------- CIRCULAR MOTION ----------------
  {
    id: "cm-1", topicId: "circular-motion", subtopic: "Centripetal acceleration", difficulty: "easy", type: "calculation",
    prompt: "A stone tied to a string moves in a horizontal circle of radius 0.5 m at a constant speed of 4 m/s. Find its centripetal acceleration.",
    correctAnswer: "32 m/s²", tolerance: 1,
    hints: { hint1: "Use a = v²/r.", hint2: "Square the speed first.", hint3: "16/0.5 = ?" },
    solution: {
      given: ["r = 0.5 m", "v = 4 m/s"], find: "centripetal acceleration",
      principle: "Any object moving in a circle at constant speed has acceleration directed toward the centre.",
      formula: "a = v²/r", whyFormula: "This is the direct formula for centripetal acceleration from speed and radius.",
      substitution: "a = 4²/0.5", calculation: ["4² = 16", "16/0.5 = 32"], units: "m/s²",
      finalAnswer: "32 m/s²", meaning: "Despite constant speed, the stone accelerates strongly toward the centre — this is what keeps it moving in a circle rather than flying off in a straight line.",
    },
    commonMistakes: ["Using diameter instead of radius.", "Forgetting to square v."], tags: ["circular motion"],
  },
  {
    id: "cm-2", topicId: "circular-motion", subtopic: "Centripetal force", difficulty: "medium", type: "scenario",
    scenario: "A car of mass 1000 kg travels around a flat, unbanked circular bend of radius 60 m at 15 m/s. The maximum friction force the tyres can provide is 3000 N.",
    prompt: "Determine whether the car can safely go round the bend at this speed.",
    correctAnswer: "No — required force (3750N) exceeds maximum friction (3000N)", tolerance: 0,
    hints: { hint1: "Find the required centripetal force for this speed and radius.", hint2: "Compare it with the maximum friction available.", hint3: "F(required) = mv²/r" },
    solution: {
      given: ["m=1000kg", "r=60m", "v=15m/s", "max friction = 3000N"], find: "Whether the car can safely turn",
      principle: "Friction provides the centripetal force needed for circular motion; if the required force exceeds the maximum available friction, the car skids.",
      formula: "F(required) = mv²/r, compare to F(max friction)",
      whyFormula: "This tells us the actual inward force needed to maintain the circular path at this speed, which friction must supply.",
      substitution: "F = 1000×15²/60", calculation: ["15²=225", "1000×225=225000", "225000/60=3750 N"],
      units: "N", finalAnswer: "Required force = 3750 N > maximum friction 3000 N, so the car CANNOT safely make the turn at 15 m/s — it will skid outward.",
      meaning: "Friction is insufficient to keep the car on its circular path at this speed; the driver must slow down before the bend.",
    },
    commonMistakes: ["Believing the car is 'thrown outward' by centrifugal force, rather than correctly reasoning that friction fails to provide enough inward force."], tags: ["circular motion", "friction"],
  },

  // ---------------- GRAVITATION ----------------
  {
    id: "gr-1", topicId: "gravitation-fields", subtopic: "Newton's law of gravitation", difficulty: "medium", type: "calculation",
    prompt: "Find the gravitational force of attraction between two 500 kg spheres whose centres are 2 m apart. (G=6.67×10⁻¹¹ N m²/kg²)",
    correctAnswer: "4.17×10⁻⁶ N", tolerance: 0.3e-6,
    hints: { hint1: "Use F = Gm1m2/r².", hint2: "Square the distance first.", hint3: "F = 6.67e-11 × 500 × 500 / 4" },
    solution: {
      given: ["m1=m2=500kg", "r=2m", "G=6.67×10⁻¹¹"], find: "gravitational force F",
      principle: "Newton's Law of Universal Gravitation.",
      formula: "F = Gm1m2/r²", whyFormula: "Direct application of the law with known masses and distance.",
      substitution: "F = 6.67e-11 × 500×500 / 2²", calculation: ["500×500=250000", "2²=4", "6.67e-11×250000=1.6675e-5", "1.6675e-5/4=4.17e-6"],
      units: "N", finalAnswer: "≈ 4.17×10⁻⁶ N", meaning: "This is an extremely tiny force — gravitational attraction between everyday-sized objects is only noticeable when at least one mass is planet-sized.",
    },
    commonMistakes: ["Forgetting to square the distance r.", "Mixing up G with g (they are very different quantities!)."], tags: ["gravitation"],
  },
  {
    id: "gr-2", topicId: "gravitation-fields", subtopic: "Orbital motion", difficulty: "exam", type: "multistep",
    scenario: "A satellite orbits Earth in a circular orbit of radius 7.0×10⁶ m. Earth's mass is 6.0×10²⁴ kg and G=6.67×10⁻¹¹ N m²/kg².",
    prompt: "Find (a) the orbital speed and (b) the orbital period of the satellite.",
    correctAnswer: "v ≈ 7.56 km/s; T ≈ 5817 s (about 97 minutes)", tolerance: 200,
    hints: { hint1: "Gravity supplies the centripetal force: GMm/r² = mv²/r.", hint2: "v = √(GM/r).", hint3: "Then use T = 2πr/v." },
    solution: {
      given: ["r = 7.0×10⁶ m", "M = 6.0×10²⁴ kg", "G = 6.67×10⁻¹¹ N m²/kg²"], find: "Orbital speed v and period T",
      principle: "Gravity provides exactly the centripetal force required to maintain the circular orbit.",
      formula: "v = √(GM/r); T = 2πr/v",
      whyFormula: "Equating gravitational force to centripetal force and cancelling the satellite's mass gives v independent of the satellite's own mass; then T follows from circumference/speed.",
      substitution: "v=√((6.67e-11×6.0e24)/7.0e6)",
      calculation: [
        "GM = 4.0×10¹⁴",
        "GM/r = 4.0×10¹⁴/7.0×10⁶ ≈ 5.71×10⁷",
        "v = √(5.71×10⁷) ≈ 7560 m/s",
        "T = 2π×7.0×10⁶/7560 ≈ 5817 s ≈ 97 minutes",
      ],
      units: "v in m/s, T in s", finalAnswer: "v ≈ 7.56 km/s, T ≈ 5817 s (~97 min)",
      meaning: "This orbit is similar to the International Space Station's — completing a full trip around Earth roughly every hour and a half.",
    },
    commonMistakes: ["Forgetting the satellite's own mass cancels out of the speed formula.", "Using diameter instead of radius."], tags: ["gravitation", "satellites"],
  },

  // ---------------- MOMENTS ----------------
  {
    id: "mm-1", topicId: "moments-equilibrium", subtopic: "Principle of moments", difficulty: "easy", type: "calculation",
    prompt: "A uniform see-saw pivoted at its centre has a 40 N child sitting 1.2 m from the pivot. How far from the pivot (on the other side) must a 60 N child sit to balance it?",
    correctAnswer: "0.8 m", tolerance: 0.05,
    hints: { hint1: "Clockwise moment = anticlockwise moment.", hint2: "40×1.2 = 60×d", hint3: "d = 48/60" },
    solution: {
      given: ["Child 1: 40 N at 1.2 m", "Child 2: 60 N at unknown distance d"], find: "distance d for balance",
      principle: "Principle of moments: for equilibrium, clockwise moments = anticlockwise moments about the pivot.",
      formula: "40 × 1.2 = 60 × d",
      whyFormula: "The see-saw balances when the two turning effects about the pivot are equal and opposite.",
      substitution: "48 = 60d", calculation: ["d = 48/60 = 0.8"],
      units: "m", finalAnswer: "0.8 m", meaning: "The heavier child must sit closer to the pivot than the lighter child for the see-saw to balance.",
    },
    commonMistakes: ["Setting weight × weight = distance × distance instead of (F×d) = (F×d)."], tags: ["moments"],
  },
  {
    id: "mm-2", topicId: "moments-equilibrium", subtopic: "Beams", difficulty: "hard", type: "scenario",
    scenario: "A uniform plank of weight 100 N and length 6 m rests horizontally on two supports, one at each end.",
    prompt: "A 50 N weight is placed 2 m from the left end. Find the reaction force at the left support.",
    correctAnswer: "75 N", tolerance: 3,
    hints: { hint1: "The plank's own weight (100N) acts at its centre (3 m from each end).", hint2: "Take moments about the RIGHT support to eliminate its unknown reaction.", hint3: "R_left × 6 = 100×3 + 50×4" },
    solution: {
      given: ["Plank weight = 100 N, acts at centre (3m from each end)", "Length = 6 m", "50 N placed 2 m from left end (so 4 m from right end)"],
      find: "Reaction at the left support, R_left",
      principle: "Taking moments about one support eliminates its own unknown reaction force, leaving one equation in one unknown.",
      formula: "Taking moments about the right support: R_left × 6 = (100×3) + (50×4)",
      whyFormula: "Moments about the right-support pivot: R_left's moment arm is the full 6m length; the plank's weight acts 3m from the right support (since it acts at the centre); the 50N weight acts 4m from the right support (6−2).",
      substitution: "R_left × 6 = 300 + 200",
      calculation: ["R_left × 6 = 500", "R_left = 500/6 ≈ 83.3 N"],
      units: "N", finalAnswer: "R_left ≈ 83.3 N",
      meaning: "Because both the plank's own weight and the extra 50N are closer to the left half overall, the left support bears more than half of the total 150N weight.",
    },
    commonMistakes: ["Forgetting the plank's own weight also produces a moment.", "Measuring distances from the wrong end when taking moments about the right support."], tags: ["moments", "beams"],
  },

  // ---------------- SHM ----------------
  {
    id: "shm-1", topicId: "shm-oscillations", subtopic: "Period of a spring", difficulty: "medium", type: "calculation",
    prompt: "A 0.4 kg mass on a spring of spring constant 40 N/m oscillates in SHM. Find the period.",
    correctAnswer: "0.63 s", tolerance: 0.05,
    hints: { hint1: "Use T = 2π√(m/k).", hint2: "First find m/k.", hint3: "√(0.4/40) = √0.01 = 0.1" },
    solution: {
      given: ["m = 0.4 kg", "k = 40 N/m"], find: "period T",
      principle: "A mass-spring system executes SHM with period depending on mass and stiffness.",
      formula: "T = 2π√(m/k)", whyFormula: "Standard SHM period formula for a spring-mass oscillator.",
      substitution: "T = 2π√(0.4/40)", calculation: ["0.4/40 = 0.01", "√0.01 = 0.1", "T = 2π(0.1) ≈ 0.628"],
      units: "s", finalAnswer: "T ≈ 0.63 s", meaning: "The mass completes a full oscillation roughly every 0.63 seconds.",
    },
    commonMistakes: ["Forgetting the square root, or forgetting to multiply by 2π."], tags: ["shm"],
  },

  // ---------------- ELASTICITY ----------------
  {
    id: "el-1", topicId: "elasticity-hooke", subtopic: "Hooke's law", difficulty: "easy", type: "calculation",
    prompt: "A spring of natural length 20 cm stretches to 26 cm under a load of 12 N. Find the spring constant.",
    correctAnswer: "200 N/m", tolerance: 10,
    hints: { hint1: "Extension = final length − natural length.", hint2: "Convert cm to m.", hint3: "k = F/x" },
    solution: {
      given: ["Natural length = 20 cm", "Stretched length = 26 cm", "F = 12 N"], find: "spring constant k",
      principle: "Hooke's Law: force is proportional to extension.",
      formula: "k = F/x, where x = extension in metres",
      whyFormula: "Rearranging F=kx for k, after finding the actual extension.",
      substitution: "x = 26−20 = 6 cm = 0.06 m; k = 12/0.06", calculation: ["k = 200"],
      units: "N/m", finalAnswer: "200 N/m", meaning: "This spring needs 200 N of force for every metre it stretches — a fairly stiff spring.",
    },
    commonMistakes: ["Forgetting to convert cm to m before dividing.", "Using the stretched length instead of the extension."], tags: ["elasticity"],
  },
  {
    id: "el-2", topicId: "elasticity-hooke", subtopic: "Elastic energy", difficulty: "medium", type: "calculation",
    prompt: "Find the elastic potential energy stored in a spring of constant 150 N/m stretched by 0.1 m.",
    correctAnswer: "0.75 J", tolerance: 0.05,
    hints: { hint1: "Use E = ½kx².", hint2: "Square the extension first.", hint3: "0.5×150×0.01" },
    solution: {
      given: ["k = 150 N/m", "x = 0.1 m"], find: "elastic potential energy",
      principle: "Elastic PE equals the area under the force-extension graph, which for Hooke's Law is ½kx².",
      formula: "E = ½kx²", whyFormula: "Straight-line force-extension graph area = triangle = ½ × base × height = ½kx².",
      substitution: "E = 0.5×150×0.1²", calculation: ["0.1²=0.01", "0.5×150×0.01=0.75"],
      units: "J", finalAnswer: "0.75 J", meaning: "This energy would be released as kinetic energy if the spring suddenly contracted back to its natural length.",
    },
    commonMistakes: ["Using E=Fx instead of E=½Fx (forgetting the factor of ½)."], tags: ["elasticity"],
  },
];

export function getQuestionsByTopic(topicId: string): Question[] {
  return QUESTION_BANK.filter((q) => q.topicId === topicId);
}
